keys:
  - &users:
    - &alex age1ftswmpx50ze6hhkf9rc2yadmq4ztakkn9xk57tweuvyfvklhyydqluekgw
  - &hosts:
    - &nixos-vm age17n60vp8ypadc0520xchgj4xf7gpwdxy8qsdsc2s0v2aavm0l3qrq6fxk4t
creation_rules:
  - path_regex: secrets(/[^/]+)?\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *alex
      - *nixos-vm
